"""朋友圈文案样本库（200 条 · 第 2 阶段 · 个人创业者沙龙场景版）

结构：每条样本 = 一条真实朋友圈文案 + 结构化标签（场景 / 情绪 / 关键词 / 来源）
规模：5 风格 × 5 场景 × 8 条 = 200 条

| 风格          | 场景 1   | 场景 2   | 场景 3 | 场景 4   | 场景 5   |
|--------------|---------|---------|--------|---------|---------|
| professional | 演讲台   | 圆桌会议 | 发布会 | 论坛    | 沙龙现场  |
| energetic    | 分享现场 | 团队合影 | 工作坊 | 交流互动 | 颁奖     |
| warm         | 私董会   | 茶歇    | 合影   | 花艺茶席 | 签到     |
| minimal      | 会场全景 | 品牌墙  | 灯光氛围| 大屏展示 | 专注聆听 |
| reflective   | 讲座    | 讨论    | 讲师特写| 嘉宾特写 | 场地布置 |

设计目的：
- 让文案生成从"旅行向模板"切换为"商务活动向模板 + 真实样本检索"
- 运营可手动追加新样本（追加后只需重启进程即可生效）

加载机制：
- 模块加载时自动调用 caption_knowledge.register_samples()
- 业务侧无需关心索引构建
"""

from __future__ import annotations

from app.ai.caption_knowledge import register_samples

SAMPLES: list[dict] = [
    # ===================== professional × 演讲台（8 条）=====================
    {"text": "站上台的那一刻，所有准备都值得。", "style": "professional",
     "scenes": ["演讲台", "分享现场"], "moods": ["专注", "坚定"],
     "keywords": ["演讲", "准备"], "source": "manual"},
    {"text": "分享的本质不是输出，是点燃。", "style": "professional",
     "scenes": ["演讲台", "讲座"], "moods": ["启发", "赋能"],
     "keywords": ["分享", "点燃"], "source": "manual"},
    {"text": "把专业讲清楚，是对听众最大的尊重。", "style": "professional",
     "scenes": ["演讲台", "论坛"], "moods": ["专业", "专注"],
     "keywords": ["专业", "听众"], "source": "manual"},
    {"text": "每一页 PPT 背后，都是十年功。", "style": "professional",
     "scenes": ["演讲台", "大屏展示"], "moods": ["坚定", "专业"],
     "keywords": ["PPT", "十年"], "source": "manual"},
    {"text": "一个人的分享，一群人的成长。", "style": "professional",
     "scenes": ["演讲台", "分享现场"], "moods": ["成长", "赋能"],
     "keywords": ["分享", "成长"], "source": "manual"},
    {"text": "专业，是把复杂的事情讲得简单。", "style": "professional",
     "scenes": ["演讲台", "讲座"], "moods": ["专业", "启发"],
     "keywords": ["专业", "简单"], "source": "manual"},
    {"text": "台上一分钟，台下是无数次迭代。", "style": "professional",
     "scenes": ["演讲台"], "moods": ["坚定", "专注"],
     "keywords": ["迭代", "准备"], "source": "manual"},
    {"text": "今天在台上，我把最好的自己交出去了。", "style": "professional",
     "scenes": ["演讲台"], "moods": ["充实", "坚定"],
     "keywords": ["分享", "自己"], "source": "manual"},

    # ===================== professional × 圆桌会议（8 条）=====================
    {"text": "圆桌的意义，是让每个声音都被听见。", "style": "professional",
     "scenes": ["圆桌会议", "讨论"], "moods": ["链接", "共鸣"],
     "keywords": ["圆桌", "声音"], "source": "manual"},
    {"text": "最好的会议，是每个人离开时都比来时更清晰。", "style": "professional",
     "scenes": ["圆桌会议", "私董会"], "moods": ["启发", "收获"],
     "keywords": ["会议", "清晰"], "source": "manual"},
    {"text": "深度对话，比任何形式都重要。", "style": "professional",
     "scenes": ["圆桌会议", "沙龙现场"], "moods": ["专注", "链接"],
     "keywords": ["对话", "深度"], "source": "manual"},
    {"text": "同频的人坐在一起，不需要太多铺垫。", "style": "professional",
     "scenes": ["圆桌会议", "私董会"], "moods": ["共鸣", "链接"],
     "keywords": ["同频", "铺垫"], "source": "manual"},
    {"text": "观点碰撞之后，共识才会浮现。", "style": "professional",
     "scenes": ["圆桌会议", "论坛"], "moods": ["启发", "收获"],
     "keywords": ["碰撞", "共识"], "source": "manual"},
    {"text": "一张圆桌，装得下所有视角。", "style": "professional",
     "scenes": ["圆桌会议"], "moods": ["链接", "包容"],
     "keywords": ["圆桌", "视角"], "source": "manual"},
    {"text": "真正的专业，是敢于在圆桌上说'我不确定'。", "style": "professional",
     "scenes": ["圆桌会议", "讨论"], "moods": ["专业", "真诚"],
     "keywords": ["专业", "不确定"], "source": "manual"},
    {"text": "每次圆桌结束，都是新合作的开始。", "style": "professional",
     "scenes": ["圆桌会议"], "moods": ["链接", "期待"],
     "keywords": ["圆桌", "合作"], "source": "manual"},

    # ===================== professional × 发布会（8 条）=====================
    {"text": "今天，我们正式启程。", "style": "professional",
     "scenes": ["发布会", "演讲台"], "moods": ["坚定", "期待"],
     "keywords": ["启程", "正式"], "source": "manual"},
    {"text": "每一个产品背后，都是无数次推翻重来。", "style": "professional",
     "scenes": ["发布会", "大屏展示"], "moods": ["坚定", "专注"],
     "keywords": ["产品", "推翻"], "source": "manual"},
    {"text": "发布会的意义，不是宣布，是交付。", "style": "professional",
     "scenes": ["发布会", "演讲台"], "moods": ["专业", "充实"],
     "keywords": ["发布会", "交付"], "source": "manual"},
    {"text": "从 0 到 1 的路上，感谢每一个见证者。", "style": "professional",
     "scenes": ["发布会", "嘉宾特写"], "moods": ["感恩", "坚定"],
     "keywords": ["见证者", "路上"], "source": "manual"},
    {"text": "这一刻，我们准备了很久。", "style": "professional",
     "scenes": ["发布会", "会场全景"], "moods": ["充实", "坚定"],
     "keywords": ["准备", "很久"], "source": "manual"},
    {"text": "产品发布，比想象中更需要勇气。", "style": "professional",
     "scenes": ["发布会", "演讲台"], "moods": ["突破", "坚定"],
     "keywords": ["勇气", "产品"], "source": "manual"},
    {"text": "把产品交出去的那一刻，一切都值了。", "style": "professional",
     "scenes": ["发布会"], "moods": ["充实", "感恩"],
     "keywords": ["产品", "交付"], "source": "manual"},
    {"text": "发布会的掌声，是对团队最好的奖励。", "style": "professional",
     "scenes": ["发布会", "颁奖"], "moods": ["感恩", "充实"],
     "keywords": ["掌声", "团队"], "source": "manual"},

    # ===================== professional × 论坛（8 条）=====================
    {"text": "论坛的意义，是让不同视角相遇。", "style": "professional",
     "scenes": ["论坛", "圆桌会议"], "moods": ["链接", "启发"],
     "keywords": ["论坛", "视角"], "source": "manual"},
    {"text": "观点没有对错，只有不同的站位。", "style": "professional",
     "scenes": ["论坛", "讨论"], "moods": ["包容", "启发"],
     "keywords": ["观点", "站位"], "source": "manual"},
    {"text": "一个好的问题，比十个答案更有价值。", "style": "professional",
     "scenes": ["论坛", "讲座"], "moods": ["启发", "专注"],
     "keywords": ["问题", "答案"], "source": "manual"},
    {"text": "今天的论坛，我记了三页笔记。", "style": "professional",
     "scenes": ["论坛", "专注聆听"], "moods": ["收获", "专注"],
     "keywords": ["论坛", "笔记"], "source": "manual"},
    {"text": "行业论坛最大的收获，是看到大家都在路上。", "style": "professional",
     "scenes": ["论坛", "交流互动"], "moods": ["共鸣", "充实"],
     "keywords": ["论坛", "路上"], "source": "manual"},
    {"text": "站在一起讨论，比各自为战更有力量。", "style": "professional",
     "scenes": ["论坛", "团队合影"], "moods": ["链接", "赋能"],
     "keywords": ["讨论", "力量"], "source": "manual"},
    {"text": "论坛结束，带走的不只是知识，还有朋友。", "style": "professional",
     "scenes": ["论坛", "交流互动"], "moods": ["收获", "链接"],
     "keywords": ["论坛", "朋友"], "source": "manual"},
    {"text": "台上嘉宾的每一句话，都值得回去反复琢磨。", "style": "professional",
     "scenes": ["论坛", "嘉宾特写"], "moods": ["启发", "专注"],
     "keywords": ["嘉宾", "琢磨"], "source": "manual"},

    # ===================== professional × 沙龙现场（8 条）=====================
    {"text": "一场好的沙龙，是让每个人都成为分享者。", "style": "professional",
     "scenes": ["沙龙现场", "分享现场"], "moods": ["链接", "赋能"],
     "keywords": ["沙龙", "分享者"], "source": "manual"},
    {"text": "沙龙的精髓，在自由讨论的那一小时。", "style": "professional",
     "scenes": ["沙龙现场", "讨论"], "moods": ["启发", "链接"],
     "keywords": ["沙龙", "讨论"], "source": "manual"},
    {"text": "今天的沙龙，话题从 2 点聊到 6 点。", "style": "professional",
     "scenes": ["沙龙现场"], "moods": ["充实", "专注"],
     "keywords": ["沙龙", "话题"], "source": "manual"},
    {"text": "小而精的沙龙，比大而全的会议更有温度。", "style": "professional",
     "scenes": ["沙龙现场", "私董会"], "moods": ["温暖", "专业"],
     "keywords": ["沙龙", "温度"], "source": "manual"},
    {"text": "在沙龙里，我听到了今年最有价值的建议。", "style": "professional",
     "scenes": ["沙龙现场", "交流互动"], "moods": ["启发", "收获"],
     "keywords": ["沙龙", "建议"], "source": "manual"},
    {"text": "主办一场沙龙，比参加一场难十倍，收获也大十倍。", "style": "professional",
     "scenes": ["沙龙现场", "场地布置"], "moods": ["成长", "充实"],
     "keywords": ["主办", "沙龙"], "source": "manual"},
    {"text": "沙龙结束，大家的微信都加了一圈。", "style": "professional",
     "scenes": ["沙龙现场", "交流互动"], "moods": ["链接", "轻松"],
     "keywords": ["沙龙", "微信"], "source": "manual"},
    {"text": "用一场沙龙，链接一群同频的人。", "style": "professional",
     "scenes": ["沙龙现场"], "moods": ["链接", "共鸣"],
     "keywords": ["沙龙", "同频"], "source": "manual"},

    # ===================== energetic × 分享现场（8 条）=====================
    {"text": "今天现场的能量，隔着屏幕都能感受到！", "style": "energetic",
     "scenes": ["分享现场", "沙龙现场"], "moods": ["赋能", "充实"],
     "keywords": ["能量", "现场"], "source": "manual"},
    {"text": "一场好的分享，是所有人一起发光。", "style": "energetic",
     "scenes": ["分享现场", "工作坊"], "moods": ["成长", "赋能"],
     "keywords": ["分享", "发光"], "source": "manual"},
    {"text": "看到大家认真记笔记的样子，一切都值了。", "style": "energetic",
     "scenes": ["分享现场", "讲座"], "moods": ["感恩", "充实"],
     "keywords": ["笔记", "认真"], "source": "manual"},
    {"text": "今天的分享会，是我这个月最期待的一天！", "style": "energetic",
     "scenes": ["分享现场", "沙龙现场"], "moods": ["期待", "兴奋"],
     "keywords": ["分享会", "期待"], "source": "manual"},
    {"text": "输出是最好的输入，这场分享我收获最大。", "style": "energetic",
     "scenes": ["分享现场", "演讲台"], "moods": ["收获", "成长"],
     "keywords": ["输出", "输入"], "source": "manual"},
    {"text": "在座的每一个人，都是这个领域的行动派。", "style": "energetic",
     "scenes": ["分享现场", "论坛"], "moods": ["赋能", "共鸣"],
     "keywords": ["行动派", "领域"], "source": "manual"},
    {"text": "分享结束，大家不走，继续聊了一小时。", "style": "energetic",
     "scenes": ["分享现场", "交流互动"], "moods": ["链接", "充实"],
     "keywords": ["分享", "交流"], "source": "manual"},
    {"text": "原来有这么多人，和我关心一样的事。", "style": "energetic",
     "scenes": ["分享现场", "沙龙现场"], "moods": ["共鸣", "温暖"],
     "keywords": ["关心", "一样"], "source": "manual"},

    # ===================== energetic × 团队合影（8 条）=====================
    {"text": "一群人，一件事，一起拼！", "style": "energetic",
     "scenes": ["团队合影", "合影"], "moods": ["赋能", "坚定"],
     "keywords": ["一群人", "拼"], "source": "manual"},
    {"text": "最好的团队，是彼此成就。", "style": "energetic",
     "scenes": ["团队合影"], "moods": ["成长", "感恩"],
     "keywords": ["团队", "成就"], "source": "manual"},
    {"text": "今天的活动圆满，全靠这支队伍。", "style": "energetic",
     "scenes": ["团队合影", "会场全景"], "moods": ["感恩", "充实"],
     "keywords": ["活动", "队伍"], "source": "manual"},
    {"text": "一个人可以走得快，一群人走得远又稳。", "style": "energetic",
     "scenes": ["团队合影", "合影"], "moods": ["链接", "坚定"],
     "keywords": ["一个人", "一群人"], "source": "manual"},
    {"text": "这张合影，值得珍藏一整年。", "style": "energetic",
     "scenes": ["团队合影"], "moods": ["感恩", "温暖"],
     "keywords": ["合影", "珍藏"], "source": "manual"},
    {"text": "团队的力量，是让我敢于迈出舒适区。", "style": "energetic",
     "scenes": ["团队合影"], "moods": ["突破", "赋能"],
     "keywords": ["团队", "舒适区"], "source": "manual"},
    {"text": "感谢每一位伙伴，今天我们都超棒！", "style": "energetic",
     "scenes": ["团队合影"], "moods": ["感恩", "充实"],
     "keywords": ["伙伴", "超棒"], "source": "manual"},
    {"text": "合影里的每一个人，都是今天的 MVP。", "style": "energetic",
     "scenes": ["团队合影", "颁奖"], "moods": ["感恩", "赋能"],
     "keywords": ["合影", "MVP"], "source": "manual"},

    # ===================== energetic × 工作坊（8 条）=====================
    {"text": "工作坊的魅力，在动手的那一刻。", "style": "energetic",
     "scenes": ["工作坊", "分享现场"], "moods": ["专注", "成长"],
     "keywords": ["工作坊", "动手"], "source": "manual"},
    {"text": "今天的工作坊，每个人都做出了自己的作品。", "style": "energetic",
     "scenes": ["工作坊"], "moods": ["充实", "收获"],
     "keywords": ["工作坊", "作品"], "source": "manual"},
    {"text": "学完马上用，这才是工作坊的正确打开方式。", "style": "energetic",
     "scenes": ["工作坊"], "moods": ["成长", "充实"],
     "keywords": ["工作坊", "学完"], "source": "manual"},
    {"text": "工作坊结束，带走的不只是笔记，是技能。", "style": "energetic",
     "scenes": ["工作坊", "讲座"], "moods": ["收获", "成长"],
     "keywords": ["工作坊", "技能"], "source": "manual"},
    {"text": "两小时的工作坊，比自学两周更高效。", "style": "energetic",
     "scenes": ["工作坊", "专注聆听"], "moods": ["成长", "启发"],
     "keywords": ["工作坊", "高效"], "source": "manual"},
    {"text": "从'我不会'到'我试试'，只差一场工作坊。", "style": "energetic",
     "scenes": ["工作坊"], "moods": ["突破", "成长"],
     "keywords": ["工作坊", "试试"], "source": "manual"},
    {"text": "工作坊的气氛太棒了，每个人都沉浸在创作里。", "style": "energetic",
     "scenes": ["工作坊"], "moods": ["专注", "充实"],
     "keywords": ["工作坊", "沉浸"], "source": "manual"},
    {"text": "下一场工作坊，已经在路上了！", "style": "energetic",
     "scenes": ["工作坊"], "moods": ["期待", "成长"],
     "keywords": ["工作坊", "路上"], "source": "manual"},

    # ===================== energetic × 交流互动（8 条）=====================
    {"text": "交流环节才是最精彩的部分！", "style": "energetic",
     "scenes": ["交流互动", "讨论"], "moods": ["链接", "充实"],
     "keywords": ["交流", "精彩"], "source": "manual"},
    {"text": "今天认识的新朋友，比过去一个月都多。", "style": "energetic",
     "scenes": ["交流互动", "茶歇"], "moods": ["链接", "收获"],
     "keywords": ["新朋友", "认识"], "source": "manual"},
    {"text": "好的活动，一半在台上，一半在台下。", "style": "energetic",
     "scenes": ["交流互动", "沙龙现场"], "moods": ["链接", "启发"],
     "keywords": ["活动", "台上台下"], "source": "manual"},
    {"text": "茶歇时间，才是真正的社交开始。", "style": "energetic",
     "scenes": ["交流互动", "茶歇"], "moods": ["轻松", "链接"],
     "keywords": ["茶歇", "社交"], "source": "manual"},
    {"text": "交换微信的那一刻，链接真正发生了。", "style": "energetic",
     "scenes": ["交流互动"], "moods": ["链接", "期待"],
     "keywords": ["微信", "链接"], "source": "manual"},
    {"text": "今天最大的收获，是找到了三个同行者。", "style": "energetic",
     "scenes": ["交流互动", "合影"], "moods": ["收获", "共鸣"],
     "keywords": ["同行者", "收获"], "source": "manual"},
    {"text": "自由交流的半小时，价值远超台上的一小时。", "style": "energetic",
     "scenes": ["交流互动", "沙龙现场"], "moods": ["链接", "收获"],
     "keywords": ["交流", "价值"], "source": "manual"},
    {"text": "原来你也在这个赛道！缘分！", "style": "energetic",
     "scenes": ["交流互动"], "moods": ["共鸣", "兴奋"],
     "keywords": ["赛道", "缘分"], "source": "manual"},

    # ===================== energetic × 颁奖（8 条）=====================
    {"text": "高光时刻！这一刻属于每一位努力的人。", "style": "energetic",
     "scenes": ["颁奖", "演讲台"], "moods": ["仪式感", "赋能"],
     "keywords": ["高光", "努力"], "source": "manual"},
    {"text": "奖杯很轻，背后的付出很重。", "style": "energetic",
     "scenes": ["颁奖"], "moods": ["感恩", "坚定"],
     "keywords": ["奖杯", "付出"], "source": "manual"},
    {"text": "今天的奖项，是对过去一年最好的交代。", "style": "energetic",
     "scenes": ["颁奖", "发布会"], "moods": ["充实", "仪式感"],
     "keywords": ["奖项", "交代"], "source": "manual"},
    {"text": "站上领奖台的那一刻，所有辛苦都化成了光。", "style": "energetic",
     "scenes": ["颁奖"], "moods": ["充实", "感恩"],
     "keywords": ["领奖台", "辛苦"], "source": "manual"},
    {"text": "每一个获奖者的背后，都有一个不放弃的故事。", "style": "energetic",
     "scenes": ["颁奖"], "moods": ["赋能", "坚定"],
     "keywords": ["获奖者", "不放弃"], "source": "manual"},
    {"text": "颁奖不是终点，是下一个阶段的起点。", "style": "energetic",
     "scenes": ["颁奖"], "moods": ["期待", "成长"],
     "keywords": ["颁奖", "起点"], "source": "manual"},
    {"text": "今晚的颁奖典礼，燃到不行！", "style": "energetic",
     "scenes": ["颁奖", "灯光氛围"], "moods": ["仪式感", "充实"],
     "keywords": ["颁奖", "燃"], "source": "manual"},
    {"text": "恭喜每一位获奖者！你们值得所有的掌声。", "style": "energetic",
     "scenes": ["颁奖"], "moods": ["赋能", "感恩"],
     "keywords": ["获奖者", "掌声"], "source": "manual"},

    # ===================== warm × 私董会（8 条）=====================
    {"text": "关上门，每个人都是彼此的老师。", "style": "warm",
     "scenes": ["私董会", "圆桌会议"], "moods": ["链接", "温暖"],
     "keywords": ["关上门", "老师"], "source": "manual"},
    {"text": "私董会结束，我带着三个答案和一群朋友离开。", "style": "warm",
     "scenes": ["私董会"], "moods": ["收获", "温暖"],
     "keywords": ["私董会", "朋友"], "source": "manual"},
    {"text": "在这里，脆弱是被允许的，成长是必然的。", "style": "warm",
     "scenes": ["私董会", "沙龙现场"], "moods": ["温暖", "成长"],
     "keywords": ["脆弱", "成长"], "source": "manual"},
    {"text": "最深的链接，往往发生在最真诚的时刻。", "style": "warm",
     "scenes": ["私董会", "交流互动"], "moods": ["链接", "真诚"],
     "keywords": ["链接", "真诚"], "source": "manual"},
    {"text": "一群人，放下手机，认真听一个人讲他的故事。", "style": "warm",
     "scenes": ["私董会", "分享现场"], "moods": ["专注", "温暖"],
     "keywords": ["放下手机", "故事"], "source": "manual"},
    {"text": "私董会不是会议，是彼此的镜子。", "style": "warm",
     "scenes": ["私董会"], "moods": ["启发", "链接"],
     "keywords": ["私董会", "镜子"], "source": "manual"},
    {"text": "谢谢你愿意把困惑说出来，我们都懂。", "style": "warm",
     "scenes": ["私董会", "圆桌会议"], "moods": ["温暖", "共鸣"],
     "keywords": ["困惑", "懂"], "source": "manual"},
    {"text": "今天之后，我们都是彼此的智囊团。", "style": "warm",
     "scenes": ["私董会"], "moods": ["链接", "感恩"],
     "keywords": ["智囊团", "彼此"], "source": "manual"},

    # ===================== warm × 茶歇（8 条）=====================
    {"text": "茶歇时间，聊出来的比台上更多。", "style": "warm",
     "scenes": ["茶歇", "交流互动"], "moods": ["轻松", "链接"],
     "keywords": ["茶歇", "聊"], "source": "manual"},
    {"text": "一杯咖啡的时间，链接了一个新朋友。", "style": "warm",
     "scenes": ["茶歇"], "moods": ["链接", "轻松"],
     "keywords": ["咖啡", "新朋友"], "source": "manual"},
    {"text": "茶歇不只是休息，是另一种形式的分享。", "style": "warm",
     "scenes": ["茶歇", "沙龙现场"], "moods": ["温暖", "轻松"],
     "keywords": ["茶歇", "分享"], "source": "manual"},
    {"text": "活动间隙的茶歇，是最放松的时刻。", "style": "warm",
     "scenes": ["茶歇"], "moods": ["轻松", "温暖"],
     "keywords": ["茶歇", "放松"], "source": "manual"},
    {"text": "甜点很甜，遇见的人更甜。", "style": "warm",
     "scenes": ["茶歇", "花艺茶席"], "moods": ["温暖", "轻松"],
     "keywords": ["甜点", "遇见"], "source": "manual"},
    {"text": "好的活动，茶歇也要用心。", "style": "warm",
     "scenes": ["茶歇", "场地布置"], "moods": ["温暖", "专业"],
     "keywords": ["茶歇", "用心"], "source": "manual"},
    {"text": "茶歇区的每一处细节，都是对来宾的尊重。", "style": "warm",
     "scenes": ["茶歇", "花艺茶席"], "moods": ["仪式感", "温暖"],
     "keywords": ["茶歇", "细节"], "source": "manual"},
    {"text": "端着咖啡聊天的十分钟，抵得上听一小时讲座。", "style": "warm",
     "scenes": ["茶歇", "交流互动"], "moods": ["链接", "启发"],
     "keywords": ["咖啡", "聊天"], "source": "manual"},

    # ===================== warm × 合影（8 条）=====================
    {"text": "这张合影里，是今天最温暖的一群人。", "style": "warm",
     "scenes": ["合影", "团队合影"], "moods": ["温暖", "感恩"],
     "keywords": ["合影", "温暖"], "source": "manual"},
    {"text": "每一次合影，都是时光的礼物。", "style": "warm",
     "scenes": ["合影"], "moods": ["温暖", "感恩"],
     "keywords": ["合影", "时光"], "source": "manual"},
    {"text": "活动结束前，必须来一张大合影。", "style": "warm",
     "scenes": ["合影", "会场全景"], "moods": ["仪式感", "温暖"],
     "keywords": ["合影", "活动结束"], "source": "manual"},
    {"text": "一张照片，装下今天所有的温度。", "style": "warm",
     "scenes": ["合影"], "moods": ["温暖", "感恩"],
     "keywords": ["照片", "温度"], "source": "manual"},
    {"text": "和喜欢的人一起做事，合影都不用喊茄子。", "style": "warm",
     "scenes": ["合影", "团队合影"], "moods": ["温暖", "轻松"],
     "keywords": ["喜欢", "合影"], "source": "manual"},
    {"text": "很多年后，我们会记得今天这张合影。", "style": "warm",
     "scenes": ["合影"], "moods": ["温暖", "感恩"],
     "keywords": ["合影", "记得"], "source": "manual"},
    {"text": "合影里每一个笑容，都是真实的。", "style": "warm",
     "scenes": ["合影"], "moods": ["温暖", "真诚"],
     "keywords": ["笑容", "真实"], "source": "manual"},
    {"text": "今天最满意的一张照片，就是这张大合照。", "style": "warm",
     "scenes": ["合影", "会场全景"], "moods": ["充实", "温暖"],
     "keywords": ["合照", "满意"], "source": "manual"},

    # ===================== warm × 花艺茶席（8 条）=====================
    {"text": "一束花，一壶茶，一场有温度的对话。", "style": "warm",
     "scenes": ["花艺茶席", "茶歇"], "moods": ["温暖", "仪式感"],
     "keywords": ["花", "茶", "对话"], "source": "manual"},
    {"text": "花艺和茶席，是今天活动最温柔的注脚。", "style": "warm",
     "scenes": ["花艺茶席", "场地布置"], "moods": ["温暖", "仪式感"],
     "keywords": ["花艺", "茶席", "温柔"], "source": "manual"},
    {"text": "细节里的用心，来宾都能感受到。", "style": "warm",
     "scenes": ["花艺茶席", "场地布置"], "moods": ["温暖", "专业"],
     "keywords": ["细节", "用心"], "source": "manual"},
    {"text": "用一束花，迎接每一位到来的人。", "style": "warm",
     "scenes": ["花艺茶席", "签到"], "moods": ["温暖", "仪式感"],
     "keywords": ["花", "迎接"], "source": "manual"},
    {"text": "品质藏在细节里，比如这束花。", "style": "warm",
     "scenes": ["花艺茶席"], "moods": ["温暖", "仪式感"],
     "keywords": ["品质", "细节", "花"], "source": "manual"},
    {"text": "茶香和花香，让今天的分享更走心。", "style": "warm",
     "scenes": ["花艺茶席", "分享现场"], "moods": ["温暖", "专注"],
     "keywords": ["茶香", "花香", "走心"], "source": "manual"},
    {"text": "一杯好茶，是对来宾最基本的尊重。", "style": "warm",
     "scenes": ["花艺茶席", "茶歇"], "moods": ["温暖", "专业"],
     "keywords": ["茶", "尊重"], "source": "manual"},
    {"text": "今天的茶席，是我亲手布置的。", "style": "warm",
     "scenes": ["花艺茶席", "场地布置"], "moods": ["充实", "仪式感"],
     "keywords": ["茶席", "布置"], "source": "manual"},

    # ===================== warm × 签到（8 条）=====================
    {"text": "每一个签到的名字，都是今天的嘉宾。", "style": "warm",
     "scenes": ["签到"], "moods": ["感恩", "仪式感"],
     "keywords": ["签到", "嘉宾"], "source": "manual"},
    {"text": "签到不是形式，是仪式感的开始。", "style": "warm",
     "scenes": ["签到"], "moods": ["仪式感", "温暖"],
     "keywords": ["签到", "仪式感"], "source": "manual"},
    {"text": "看到签到表上写满名字，心里满满的。", "style": "warm",
     "scenes": ["签到"], "moods": ["感恩", "充实"],
     "keywords": ["签到表", "名字"], "source": "manual"},
    {"text": "感谢每一位如约而至的你。", "style": "warm",
     "scenes": ["签到", "嘉宾特写"], "moods": ["感恩", "温暖"],
     "keywords": ["如约而至", "感谢"], "source": "manual"},
    {"text": "签到处，是今天第一声问候的地方。", "style": "warm",
     "scenes": ["签到"], "moods": ["温暖", "仪式感"],
     "keywords": ["签到处", "问候"], "source": "manual"},
    {"text": "每一笔签到，都是一份信任。", "style": "warm",
     "scenes": ["签到"], "moods": ["感恩", "温暖"],
     "keywords": ["签到", "信任"], "source": "manual"},
    {"text": "签到的这一刻，活动才算真正开始了。", "style": "warm",
     "scenes": ["签到"], "moods": ["仪式感", "期待"],
     "keywords": ["签到", "开始"], "source": "manual"},
    {"text": "今天签到的每一位，都值得被记住。", "style": "warm",
     "scenes": ["签到", "合影"], "moods": ["感恩", "温暖"],
     "keywords": ["签到", "记住"], "source": "manual"},

    # ===================== minimal × 会场全景（8 条）=====================
    {"text": "会场。", "style": "minimal",
     "scenes": ["会场全景"], "moods": ["专注"], "keywords": ["会场"], "source": "manual"},
    {"text": "今天的场。", "style": "minimal",
     "scenes": ["会场全景", "场地布置"], "moods": ["仪式感"], "keywords": ["场"], "source": "manual"},
    {"text": "准备就绪。", "style": "minimal",
     "scenes": ["会场全景"], "moods": ["期待", "专注"], "keywords": ["准备"], "source": "manual"},
    {"text": "坐满。", "style": "minimal",
     "scenes": ["会场全景", "专注聆听"], "moods": ["充实"], "keywords": ["坐满"], "source": "manual"},
    {"text": "此刻，会场。", "style": "minimal",
     "scenes": ["会场全景"], "moods": ["仪式感"], "keywords": ["会场"], "source": "manual"},
    {"text": "场已备好。", "style": "minimal",
     "scenes": ["会场全景", "场地布置"], "moods": ["期待"], "keywords": ["场"], "source": "manual"},
    {"text": "满。", "style": "minimal",
     "scenes": ["会场全景"], "moods": ["充实"], "keywords": ["满"], "source": "manual"},
    {"text": "布置完成。", "style": "minimal",
     "scenes": ["会场全景", "场地布置"], "moods": ["仪式感"], "keywords": ["布置"], "source": "manual"},

    # ===================== minimal × 品牌墙（8 条）=====================
    {"text": "品牌墙。", "style": "minimal",
     "scenes": ["品牌墙"], "moods": ["坚定"], "keywords": ["品牌"], "source": "manual"},
    {"text": "每一次积累。", "style": "minimal",
     "scenes": ["品牌墙"], "moods": ["成长", "坚定"], "keywords": ["积累"], "source": "manual"},
    {"text": "品牌之路。", "style": "minimal",
     "scenes": ["品牌墙"], "moods": ["坚定"], "keywords": ["品牌", "路"], "source": "manual"},
    {"text": "从 0 到 1。", "style": "minimal",
     "scenes": ["品牌墙", "发布会"], "moods": ["成长", "坚定"], "keywords": ["0", "1"], "source": "manual"},
    {"text": "看得见的成长。", "style": "minimal",
     "scenes": ["品牌墙"], "moods": ["成长", "充实"], "keywords": ["成长"], "source": "manual"},
    {"text": "沉淀。", "style": "minimal",
     "scenes": ["品牌墙"], "moods": ["坚定"], "keywords": ["沉淀"], "source": "manual"},
    {"text": "品牌 / 时间。", "style": "minimal",
     "scenes": ["品牌墙"], "moods": ["坚定", "专注"], "keywords": ["品牌", "时间"], "source": "manual"},
    {"text": "记录。", "style": "minimal",
     "scenes": ["品牌墙"], "moods": ["充实"], "keywords": ["记录"], "source": "manual"},

    # ===================== minimal × 灯光氛围（8 条）=====================
    {"text": "灯。", "style": "minimal",
     "scenes": ["灯光氛围", "会场全景"], "moods": ["仪式感"], "keywords": ["灯"], "source": "manual"},
    {"text": "光。", "style": "minimal",
     "scenes": ["灯光氛围"], "moods": ["专注"], "keywords": ["光"], "source": "manual"},
    {"text": "氛围。", "style": "minimal",
     "scenes": ["灯光氛围"], "moods": ["仪式感"], "keywords": ["氛围"], "source": "manual"},
    {"text": "恰到好处的光。", "style": "minimal",
     "scenes": ["灯光氛围"], "moods": ["仪式感", "温暖"], "keywords": ["光"], "source": "manual"},
    {"text": "灯光就位。", "style": "minimal",
     "scenes": ["灯光氛围", "会场全景"], "moods": ["期待"], "keywords": ["灯光"], "source": "manual"},
    {"text": "暖。", "style": "minimal",
     "scenes": ["灯光氛围"], "moods": ["温暖"], "keywords": ["暖"], "source": "manual"},
    {"text": "影。", "style": "minimal",
     "scenes": ["灯光氛围"], "moods": ["仪式感"], "keywords": ["影"], "source": "manual"},
    {"text": "光 / 影 / 场。", "style": "minimal",
     "scenes": ["灯光氛围", "会场全景"], "moods": ["仪式感"], "keywords": ["光", "影", "场"], "source": "manual"},

    # ===================== minimal × 大屏展示（8 条）=====================
    {"text": "大屏。", "style": "minimal",
     "scenes": ["大屏展示", "演讲台"], "moods": ["专业"], "keywords": ["大屏"], "source": "manual"},
    {"text": "PPT。", "style": "minimal",
     "scenes": ["大屏展示"], "moods": ["专注"], "keywords": ["PPT"], "source": "manual"},
    {"text": "内容。", "style": "minimal",
     "scenes": ["大屏展示", "讲座"], "moods": ["专业"], "keywords": ["内容"], "source": "manual"},
    {"text": "分享 / 大屏。", "style": "minimal",
     "scenes": ["大屏展示", "分享现场"], "moods": ["专注"], "keywords": ["分享", "大屏"], "source": "manual"},
    {"text": "正在分享。", "style": "minimal",
     "scenes": ["大屏展示", "演讲台"], "moods": ["专注"], "keywords": ["分享"], "source": "manual"},
    {"text": "屏幕。", "style": "minimal",
     "scenes": ["大屏展示"], "moods": ["专注"], "keywords": ["屏幕"], "source": "manual"},
    {"text": "价值输出中。", "style": "minimal",
     "scenes": ["大屏展示", "演讲台"], "moods": ["专业", "充实"], "keywords": ["输出"], "source": "manual"},
    {"text": "第 N 页。", "style": "minimal",
     "scenes": ["大屏展示"], "moods": ["专注"], "keywords": ["页"], "source": "manual"},

    # ===================== minimal × 专注聆听（8 条）=====================
    {"text": "听。", "style": "minimal",
     "scenes": ["专注聆听", "讲座"], "moods": ["专注"], "keywords": ["听"], "source": "manual"},
    {"text": "认真。", "style": "minimal",
     "scenes": ["专注聆听"], "moods": ["专注"], "keywords": ["认真"], "source": "manual"},
    {"text": "沉浸。", "style": "minimal",
     "scenes": ["专注聆听", "分享现场"], "moods": ["专注"], "keywords": ["沉浸"], "source": "manual"},
    {"text": "眼里有光。", "style": "minimal",
     "scenes": ["专注聆听"], "moods": ["专注", "启发"], "keywords": ["光"], "source": "manual"},
    {"text": "此刻，专注。", "style": "minimal",
     "scenes": ["专注聆听", "讲座"], "moods": ["专注"], "keywords": ["专注"], "source": "manual"},
    {"text": "笔记中。", "style": "minimal",
     "scenes": ["专注聆听"], "moods": ["专注", "收获"], "keywords": ["笔记"], "source": "manual"},
    {"text": "听众。", "style": "minimal",
     "scenes": ["专注聆听"], "moods": ["专注"], "keywords": ["听众"], "source": "manual"},
    {"text": "全场安静。", "style": "minimal",
     "scenes": ["专注聆听", "会场全景"], "moods": ["专注", "仪式感"], "keywords": ["安静"], "source": "manual"},

    # ===================== reflective × 讲座（8 条）=====================
    {"text": "一场讲座下来，最大的收获是重新认识了自己。", "style": "reflective",
     "scenes": ["讲座", "演讲台"], "moods": ["启发", "成长"],
     "keywords": ["讲座", "认识"], "source": "manual"},
    {"text": "有些观点，要听完一整场讲座才能理解。", "style": "reflective",
     "scenes": ["讲座", "专注聆听"], "moods": ["启发", "专注"],
     "keywords": ["观点", "理解"], "source": "manual"},
    {"text": "讲座结束，我坐在位子上想了很久。", "style": "reflective",
     "scenes": ["讲座"], "moods": ["启发", "专注"],
     "keywords": ["讲座", "想"], "source": "manual"},
    {"text": "一个好讲座，不是给你答案，是给你问题。", "style": "reflective",
     "scenes": ["讲座", "论坛"], "moods": ["启发", "成长"],
     "keywords": ["讲座", "问题"], "source": "manual"},
    {"text": "今天讲座里有一句话，我记了三遍。", "style": "reflective",
     "scenes": ["讲座", "专注聆听"], "moods": ["启发", "收获"],
     "keywords": ["讲座", "一句话"], "source": "manual"},
    {"text": "听完讲座，回去的路上一直在复盘。", "style": "reflective",
     "scenes": ["讲座"], "moods": ["启发", "成长"],
     "keywords": ["讲座", "复盘"], "source": "manual"},
    {"text": "有些道理，要坐在台下才能真正听进去。", "style": "reflective",
     "scenes": ["讲座", "专注聆听"], "moods": ["启发", "成长"],
     "keywords": ["道理", "台下"], "source": "manual"},
    {"text": "讲座的价值不在现场，在回去之后的行动。", "style": "reflective",
     "scenes": ["讲座"], "moods": ["启发", "成长"],
     "keywords": ["讲座", "行动"], "source": "manual"},

    # ===================== reflective × 讨论（8 条）=====================
    {"text": "最好的讨论，是没有标准答案的那种。", "style": "reflective",
     "scenes": ["讨论", "圆桌会议"], "moods": ["启发", "链接"],
     "keywords": ["讨论", "答案"], "source": "manual"},
    {"text": "一场深度讨论，胜过独自思考一个月。", "style": "reflective",
     "scenes": ["讨论", "私董会"], "moods": ["启发", "成长"],
     "keywords": ["讨论", "思考"], "source": "manual"},
    {"text": "在讨论中，我发现了自己的盲区。", "style": "reflective",
     "scenes": ["讨论", "交流互动"], "moods": ["启发", "成长"],
     "keywords": ["讨论", "盲区"], "source": "manual"},
    {"text": "讨论到最后，问题比开始时更清晰了。", "style": "reflective",
     "scenes": ["讨论", "圆桌会议"], "moods": ["启发", "收获"],
     "keywords": ["讨论", "清晰"], "source": "manual"},
    {"text": "有些话，只有在讨论中才会被说出来。", "style": "reflective",
     "scenes": ["讨论", "私董会"], "moods": ["真诚", "启发"],
     "keywords": ["讨论", "话"], "source": "manual"},
    {"text": "今天讨论的这个问题，我会想很久。", "style": "reflective",
     "scenes": ["讨论", "论坛"], "moods": ["启发", "专注"],
     "keywords": ["讨论", "问题"], "source": "manual"},
    {"text": "讨论不是说服对方，是共同逼近真相。", "style": "reflective",
     "scenes": ["讨论", "圆桌会议"], "moods": ["启发", "链接"],
     "keywords": ["讨论", "真相"], "source": "manual"},
    {"text": "真正的思考，从讨论结束那一刻才开始。", "style": "reflective",
     "scenes": ["讨论"], "moods": ["启发", "成长"],
     "keywords": ["思考", "讨论"], "source": "manual"},

    # ===================== reflective × 讲师特写（8 条）=====================
    {"text": "站在台上的人，都有不为人知的准备。", "style": "reflective",
     "scenes": ["讲师特写", "演讲台"], "moods": ["启发", "感恩"],
     "keywords": ["台上", "准备"], "source": "manual"},
    {"text": "讲师的每一句话，都是踩过坑之后的心得。", "style": "reflective",
     "scenes": ["讲师特写", "讲座"], "moods": ["启发", "共鸣"],
     "keywords": ["讲师", "心得"], "source": "manual"},
    {"text": "看着讲师，我在想：什么时候我也能站上去？", "style": "reflective",
     "scenes": ["讲师特写", "演讲台"], "moods": ["启发", "成长"],
     "keywords": ["讲师", "站上去"], "source": "manual"},
    {"text": "真诚是最好的表达方式，讲师做到了。", "style": "reflective",
     "scenes": ["讲师特写", "分享现场"], "moods": ["启发", "共鸣"],
     "keywords": ["真诚", "讲师"], "source": "manual"},
    {"text": "一个眼神，一个停顿，都是功力的体现。", "style": "reflective",
     "scenes": ["讲师特写"], "moods": ["专注", "启发"],
     "keywords": ["眼神", "功力"], "source": "manual"},
    {"text": "讲师今天的一句话，解了我半年的困惑。", "style": "reflective",
     "scenes": ["讲师特写", "讲座"], "moods": ["启发", "收获"],
     "keywords": ["讲师", "困惑"], "source": "manual"},
    {"text": "台上的光鲜，是台下无数个深夜换来的。", "style": "reflective",
     "scenes": ["讲师特写", "演讲台"], "moods": ["启发", "坚定"],
     "keywords": ["光鲜", "深夜"], "source": "manual"},
    {"text": "好的讲师，不是在教，是在点燃。", "style": "reflective",
     "scenes": ["讲师特写", "分享现场"], "moods": ["启发", "赋能"],
     "keywords": ["讲师", "点燃"], "source": "manual"},

    # ===================== reflective × 嘉宾特写（8 条）=====================
    {"text": "每一位嘉宾，都是这个行业的灯塔。", "style": "reflective",
     "scenes": ["嘉宾特写", "论坛"], "moods": ["启发", "感恩"],
     "keywords": ["嘉宾", "灯塔"], "source": "manual"},
    {"text": "嘉宾的一句话，值得反复回味。", "style": "reflective",
     "scenes": ["嘉宾特写", "讲座"], "moods": ["启发", "收获"],
     "keywords": ["嘉宾", "回味"], "source": "manual"},
    {"text": "和嘉宾对视的那一刻，我读懂了很多。", "style": "reflective",
     "scenes": ["嘉宾特写", "专注聆听"], "moods": ["共鸣", "启发"],
     "keywords": ["嘉宾", "对视"], "source": "manual"},
    {"text": "嘉宾分享的不仅是经验，是走过的路。", "style": "reflective",
     "scenes": ["嘉宾特写", "分享现场"], "moods": ["启发", "成长"],
     "keywords": ["嘉宾", "路"], "source": "manual"},
    {"text": "从嘉宾身上，我看到了自己想成为的样子。", "style": "reflective",
     "scenes": ["嘉宾特写"], "moods": ["启发", "成长"],
     "keywords": ["嘉宾", "样子"], "source": "manual"},
    {"text": "嘉宾说话的时候，全场都安静了。", "style": "reflective",
     "scenes": ["嘉宾特写", "专注聆听"], "moods": ["专注", "启发"],
     "keywords": ["嘉宾", "安静"], "source": "manual"},
    {"text": "谢谢每一位嘉宾，愿意把时间留给我们。", "style": "reflective",
     "scenes": ["嘉宾特写", "颁奖"], "moods": ["感恩", "温暖"],
     "keywords": ["嘉宾", "时间"], "source": "manual"},
    {"text": "嘉宾身上的光芒，来自无数个不为人知的日夜。", "style": "reflective",
     "scenes": ["嘉宾特写", "演讲台"], "moods": ["启发", "坚定"],
     "keywords": ["嘉宾", "光芒"], "source": "manual"},

    # ===================== reflective × 场地布置（8 条）=====================
    {"text": "每一处布置，都是对活动的一次承诺。", "style": "reflective",
     "scenes": ["场地布置", "会场全景"], "moods": ["仪式感", "坚定"],
     "keywords": ["布置", "承诺"], "source": "manual"},
    {"text": "布置场地的时候，心里想的是来宾的感受。", "style": "reflective",
     "scenes": ["场地布置"], "moods": ["温暖", "专注"],
     "keywords": ["布置", "来宾"], "source": "manual"},
    {"text": "一场活动好不好，看布置就知道。", "style": "reflective",
     "scenes": ["场地布置", "会场全景"], "moods": ["专业", "仪式感"],
     "keywords": ["活动", "布置"], "source": "manual"},
    {"text": "细节里有主办方的用心，也有品牌的温度。", "style": "reflective",
     "scenes": ["场地布置", "花艺茶席"], "moods": ["温暖", "专业"],
     "keywords": ["细节", "温度"], "source": "manual"},
    {"text": "布置完成的那一刻，心里才踏实。", "style": "reflective",
     "scenes": ["场地布置"], "moods": ["充实", "期待"],
     "keywords": ["布置", "踏实"], "source": "manual"},
    {"text": "每一次布置，都是对品牌的一次重新定义。", "style": "reflective",
     "scenes": ["场地布置", "品牌墙"], "moods": ["坚定", "成长"],
     "keywords": ["布置", "品牌"], "source": "manual"},
    {"text": "从空场地到满场，中间是无数个细节。", "style": "reflective",
     "scenes": ["场地布置", "会场全景"], "moods": ["充实", "仪式感"],
     "keywords": ["空场地", "细节"], "source": "manual"},
    {"text": "布置完场地，站在门口看了一眼，值了。", "style": "reflective",
     "scenes": ["场地布置"], "moods": ["充实", "感恩"],
     "keywords": ["布置", "门口"], "source": "manual"},
]


# 模块加载时自动注册到 caption_knowledge 的索引中
register_samples(SAMPLES)


def get_sample_stats() -> dict:
    """统计样本库分布（用于监控 / 调试）"""
    from collections import Counter
    style_counter: Counter[str] = Counter()
    scene_counter: Counter[str] = Counter()
    source_counter: Counter[str] = Counter()
    for s in SAMPLES:
        style_counter[s.get("style", "unknown")] += 1
        for sc in s.get("scenes", []):
            scene_counter[sc] += 1
        source_counter[s.get("source", "unknown")] += 1
    return {
        "total": len(SAMPLES),
        "by_style": dict(style_counter),
        "by_scene_top10": dict(scene_counter.most_common(10)),
        "by_source": dict(source_counter),
    }
